# Top-level configuration
name = 'stuuff'
main = "src/index.js"
compatibility_date = "2022-07-12"

workers_dev = false
route = { pattern = "example.org/*", zone_name = "example.org" }

[env.staging]
name = "my-worker-staging"
route = { pattern = "staging.example.org/*", zone_name = "example.org" }

kv_namespaces = [
  { binding = "<MY_NAMESPACE>", id = "<STAGING_KV_ID>" }
]
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
